{"name": "test_login_invalid_data_401[email]", "status": "passed", "parameters": [{"name": "key", "value": "'email'"}], "start": 1741766423591, "stop": 1741766423714, "uuid": "fa9e328c-749c-4547-b576-f93425c43384", "historyId": "d2bbedebdd7c81dd58d2160e500f515e", "testCaseId": "40f1be16d719b470d6b33a0dcfa51542", "fullName": "tests.test_login.TestLogin#test_login_invalid_data_401", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-4NMQM7J"}, {"name": "thread", "value": "18044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}